---
title: "01f-timeseries-NODEBNGMpaper"
date: "Compiled at `r format(Sys.time(), '%Y-%m-%d %H:%M:%S', tz = 'UTC')` UTC"
output: github_document
params:
  name: "01f-timeseries-NODEBNGMpaper" # change if you rename file
---

```{r here, message=FALSE}
here::i_am(paste0(params$name, ".Rmd"), uuid = "9506fa44-f8a3-401c-aa4c-950659e05f3f")
```

The purpose of this document is to collect the datasets from https://github.com/WillemBonnaffe/NODEBNGM/tree/main/data .

```{r packages, message=FALSE}
library("conflicted")
library(data.table)
library(dplyr)
library(ggplot2)
library(phyloseq)

```

```{r directories}
# create or *empty* the target directory, used to write this file's data: 
projthis::proj_create_dir_target(params$name, clean = TRUE)

# function to get path to target directory: path_target("sample.csv")
path_target <- projthis::proj_path_target(params$name)

# function to get path to previous data: path_source("00-import", "sample.csv")
path_source <- projthis::proj_path_source(params$name)
```

## Read Data and make Phyloseq objects

```{r}
folderpath_data <-
  "input_data/NODEBNGM/"

files <- c("3DLV",
           "AFR1",
           "AFR2",
           "AFR3",
           "RPS")

for(ts_name in files) {
  tmp <-
    fread(paste0(folderpath_data, "TS_", ts_name, ".csv"), header = T) %>%
    .[, SampleID := sprintf("ID-%03d", t)] %>%
    tibble::column_to_rownames("SampleID") %>%
    rename(Time = t)
  
  assign(paste0("dt_", ts_name),
         tmp)
}

dt_HL <-
  fread(paste0(folderpath_data, "TS_HL.csv"), header = T) %>%
    .[, SampleID := sprintf("ID-%03d", as.numeric(row.names(.)))] %>%
    tibble::column_to_rownames("SampleID") %>%
    rename(Time = Year)

files <- c(files, "HL")

# convert to phyloseq after reading the data
for(ts_name in files) {
  tmp_otu <-
    get(paste0("dt_", ts_name)) %>% 
    subset(select = -Time) %>% 
    t() %>% 
    otu_table(taxa_are_rows = T)
  
  tmp_sample <-
    get(paste0("dt_", ts_name)) %>% 
    subset(select = Time) %>% 
    sample_data()

  assign(paste0("ps_", ts_name),
         phyloseq(tmp_otu, tmp_sample))
}

rm(tmp, tmp_otu, tmp_sample)

```


### Ushio Dataset

```{r}
# special case (including more sample info): Ushio
dt_Ushio_raw <-
  fread(paste0(folderpath_data, "TS_Ushio.csv")) %>%
  .[, SampleID := sprintf("ID-%03d", time_step)] %>%
  tibble::column_to_rownames("SampleID")

# otu table
dt_Ushio <-
  dt_Ushio_raw %>% select(
    "Aurelia.sp",
    "Engraulis.japonicus",
    "Plotosus.lineatus",
    "Sebastes.inermis",
    "Trachurus.japonicus",
    "Girella.punctata",
    "Pseudolabrus.sieboldi",
    "Halichoeres.poecilopterus",
    "Halichoeres.tenuispinnis",
    "Chaenogobius.gulosus",
    "Pterogobius.zonoleucus",
    "Tridentiger.trigonocephalus",
    "Siganus.fuscescens",
    "Sphyraena.pinguis",
    "Rudarius.ercodes"
  )

otu_Ushio <-
  copy(dt_Ushio) %>% 
  t() %>% 
  otu_table(taxa_are_rows = T)

# sample info
samples_Ushio <-
  dt_Ushio_raw %>%
  select("date_tag", "surf.t", "bot.t", "Y", "M", "D", "time_step")
samples_Ushio$Day <-
  as.Date(paste0(samples_Ushio$Y, "-", samples_Ushio$M, "-", 
                 samples_Ushio$D), 
          format = "%Y-%m-%d")
# Mutate the Time column to be the integer day starting with 1
samples_Ushio <- samples_Ushio %>% 
  mutate(Time = as.numeric(difftime(Day, min(Day), units = "days")) + 1)

# taxonomic table
tax_Ushio <- 
  fread(paste0(folderpath_data, "tax_table_Ushio.csv")) %>% 
  as.matrix()
rownames(tax_Ushio) <- tax_Ushio[, "Species"]


# make phyloseq object
ps_Ushio <-
  phyloseq(otu_Ushio, 
           tax_table(tax_Ushio),
           sample_data(samples_Ushio))

# add Ushio to list of files
files <- c(files, "Ushio")
```


### 3DLV Data

Only keep values in the interval [0, 60].

```{r}
ps_3DLV <- subset_samples(ps_3DLV, Time <= 60)
```


### Overview over the phyloseq objects

```{r}
for(ts_name in files) {
  cat(ts_name, "\n")
  print(get(paste0("ps_", ts_name)))
  cat("\n")
}
```


## Plot Datasets

```{r}
for(ts_name in files) {
  ps_tmp <-
      psmelt(get(paste0("ps_", ts_name)))
  plt_tmp <-
    ggplot(ps_tmp, aes(x = Time, y = Abundance, col = OTU)) +
    geom_line() +
    labs(title = ts_name,
         subtitle = paste0("number of time points: ", uniqueN(ps_tmp[,1])),
         x = "Time")
  print(plt_tmp)
}

```


## Get relative abundances 

### for TS_RPS

```{r}
# calculcate relative abundances
ps_RPS_rel_counts <-
  transform_sample_counts(ps_RPS, function(x) x / sum(x))

# bar plot phyloseq objects
plot_bar(ps_RPS_rel_counts, x = "Time", fill = "OTU") +
  geom_bar(aes(color = OTU, fill = OTU), stat = "identity", position = "stack") +
  labs(title = "RPS, relative Abundances",
       x = "Time")

```


## Save Phyloseq Objects

```{r}
for (ts_name in c(files, "RPS_rel_counts")) {
  saveRDS(get(paste0("ps_", ts_name)),
          path_target(paste0("ps_", ts_name, ".rds")))
}
```



## Save TS as csv file

```{r}
for (ts_name in c(files, "RPS_rel_counts")) {
  
  # get the tmp phyloseq object
  ps_obj <- get(paste0("ps_", ts_name))
  
  if(taxa_are_rows(ps_obj)) {
    otu_tmp <- t(otu_table(ps_obj))
  } else {
    otu_tmp <- otu_table(ps_obj)
  }
  # combine count data with time information
  ts_obj <-
    cbind(sample_data(ps_obj)[, "Time"],
          otu_tmp)
  # print(head(ts_obj))
  
  # save time series as csv file
  write.csv(
    ts_obj,
    path_target(paste0("ts_", ts_name, ".csv")),
    row.names = F
  )
    
}

```


## Files written

These files have been written to the target directory, ```r paste0("data/", params$name)```:

```{r list-files-target}
projthis::proj_dir_info(path_target())
```
